<template>
  <!-- =====================================================================
       STATE 1 — Grand-final week (is_grand_final && !is_post_season):
       the home page becomes the pre-match grand-final report.  If the
       report hasn't been generated yet (404) it falls back to the
       standard detail experience for the game.
       ===================================================================== -->
  <template v-if="isGrandFinal">
    <div v-if="grandFinalPending" class="loading" role="status" aria-live="polite">
      <div class="spinner"></div>
    </div>

    <GrandFinalReport
      v-else-if="grandFinalReport && grandFinalGame"
      :report="grandFinalReport"
      :game="grandFinalGame"
    />

    <!-- Report not yet generated → standard detail experience -->
    <div v-else-if="grandFinalDetail" class="section gf-fallback">
      <section class="gf-header">
        <span class="gf-eyebrow">Grand Final</span>
        <div class="teams">
          <div class="team home">
            <img :src="getLogoUrl(grandFinalDetail.game.home_team ?? 'TBD')" :alt="`${grandFinalDetail.game.home_team ?? 'TBD'} logo`" class="team-logo" loading="lazy" decoding="async" width="80" height="80" />
            <span class="team-name">{{ getTeamDisplayName(grandFinalDetail.game.home_team) }}</span>
          </div>
          <span class="vs">VS</span>
          <div class="team away">
            <img :src="getLogoUrl(grandFinalDetail.game.away_team ?? 'TBD')" :alt="`${grandFinalDetail.game.away_team ?? 'TBD'} logo`" class="team-logo" loading="lazy" decoding="async" width="80" height="80" />
            <span class="team-name">{{ getTeamDisplayName(grandFinalDetail.game.away_team) }}</span>
          </div>
        </div>
        <div class="game-meta">
          <div class="meta-item">
            <span class="label">Venue:</span>
            <span class="value">{{ grandFinalDetail.game.venue ?? 'TBD' }}</span>
          </div>
          <div class="meta-item">
            <span class="label">Date:</span>
            <span class="value">{{ grandFinalDetail.game.date ? formatDate(grandFinalDetail.game.date) : 'TBD' }}</span>
          </div>
        </div>
      </section>

      <!-- REVIEW-MAJOR-3: the report is generated by the nightly cron and
           may land after this page loaded — the poller adopts it
           automatically (see onMounted below); this button forces an
           immediate attempt without waiting for the next poll. -->
      <div class="gf-report-hint">
        <button @click="refreshGrandFinal" class="btn">Load full report</button>
      </div>

      <section v-if="grandFinalDetail.weather" class="gf-section-block">
        <h2 class="section-title">Weather Conditions</h2>
        <WeatherCard :weather="grandFinalDetail.weather" />
      </section>

      <section class="gf-section-block">
        <h2 class="section-title">Heuristic Tips</h2>
        <div class="tips-grid">
          <TipCard
            v-for="tip in grandFinalDetail.tips"
            :key="tip.id"
            :heuristic="tip.heuristic"
            :selected-team="tip.selected_team"
            :margin="tip.margin"
            :confidence="tip.confidence"
            :explanation="tip.explanation"
          />
        </div>
      </section>

      <section class="gf-section-block">
        <h2 class="section-title">Model Predictions</h2>
        <div class="models-grid">
          <div
            v-for="prediction in grandFinalDetail.model_predictions"
            :key="prediction.model_name"
            class="model-card"
          >
            <div class="model-header">
              <span class="model-name">{{ getModelDisplayName(prediction.model_name) }}</span>
              <span class="confidence">{{ Math.round(prediction.confidence * 100) }}%</span>
            </div>
            <div class="model-body">
              <h3>{{ prediction.winner }}</h3>
              <p class="margin">Margin: {{ prediction.margin }} pts</p>
            </div>
          </div>
        </div>
      </section>

      <section v-if="grandFinalDetail.match_analysis" class="gf-section-block">
        <h2 class="section-title">Match Analysis</h2>
        <MatchAnalysisCard :analysis="grandFinalDetail.match_analysis" />
      </section>
    </div>

    <div v-else class="section gf-unavailable">
      <p>The grand final preview isn't available yet. Check back soon.</p>
      <button @click="refreshGrandFinal" class="btn">Retry</button>
    </div>
  </template>

  <!-- =====================================================================
       STATE 2 — Post-season (is_post_season): off-season celebration.
       ===================================================================== -->
  <OffSeasonCelebration
    v-else-if="isPostSeason"
    :premier="round?.premier ?? null"
    :season="round?.season ?? null"
  />

  <!-- =====================================================================
       STATE 3 — Regular round: the original home page, unchanged.
       ===================================================================== -->
  <template v-else>
      <section class="hero">
        <h1>AI-Powered<br>Footy Tipping</h1>
        <p>Smart heuristics. Clear explanations. Better tips.</p>
      </section>

      <section class="section">
        <!-- Round Display -->
        <div v-if="round" class="round-display">
          <span class="round-label">{{ round.is_current_year ? 'Current Round' : 'Latest Available' }}</span>
          <span class="round-value">R{{ round.round_id }} • {{ round.season }}</span>
          <span class="game-count">{{ round.game_count }} Games</span>
        </div>

        <!-- Data Warning -->
        <div v-if="round && !round.is_current_year" class="data-warning">
          <p>
            <strong>No data available for {{ new Date().getFullYear() }}.</strong>
            Showing historical data from {{ round.season }}.
          </p>
        </div>

        <!-- Heuristic Selector -->
        <div class="heuristic-selector" role="tablist" aria-label="Heuristic filter">
          <button
            v-for="h in heuristics"
            :key="h.value"
            role="tab"
            :aria-selected="selectedHeuristic === h.value"
            @click="selectedHeuristic = h.value"
            :class="['heuristic-btn', { active: selectedHeuristic === h.value }]"
          >
            {{ h.label }}
          </button>
        </div>

        <!-- Games with Tips -->
        <Transition name="fade" mode="out-in">
          <div :key="selectedHeuristic">
            <div v-if="loading" class="loading" role="status" aria-live="polite">
              <div class="spinner"></div>
            </div>
            <div v-else-if="error" class="error" role="status" aria-live="polite">
              <p>{{ error }}</p>
              <button @click="refreshAll" class="btn">Retry</button>
            </div>
            <div v-else-if="gamesWithTips.length === 0" class="empty" role="status" aria-live="polite">
              <p>No tips available for this round yet.</p>
              <p class="empty-hint">Tips are generated automatically after each round's data sync.</p>
            </div>
            <div v-else class="games-grid">
            <NuxtLink
              v-for="game in gamesWithTips"
              :key="game.id"
              :to="`/game/${game.slug}`"
              class="game-card-link"
            >
              <div class="game-card">
                <!-- Match Info -->
              <div class="match-info">
                <div class="teams">
                  <div class="team home">
                    <img :src="getLogoUrl(game.home_team ?? 'TBD')" :alt="`${game.home_team ?? 'TBD'} logo`" class="team-logo" loading="lazy" decoding="async" width="40" height="40" />
                    <!-- DESIGN-FIX: logos alone assumed badge recognition —
                         show the name so the matchup is readable at a glance -->
                    <span class="team-name">{{ getTeamDisplayName(game.home_team) }}</span>
                  </div>
                  <span class="vs">VS</span>
                  <div class="team away">
                    <img :src="getLogoUrl(game.away_team ?? 'TBD')" :alt="`${game.away_team ?? 'TBD'} logo`" class="team-logo" loading="lazy" decoding="async" width="40" height="40" />
                    <span class="team-name">{{ getTeamDisplayName(game.away_team) }}</span>
                  </div>
                </div>
                <div class="match-details">
                  <span class="venue">{{ game.venue ?? 'TBD' }}</span>
                  <span class="date">{{ game.date ? formatDate(game.date) : 'TBD' }}</span>
                </div>
              </div>

              <!-- Tip Info -->
              <div v-if="game.tip" class="tip-info">
                <div class="tip-header">
                  <span class="heuristic-badge">{{ formatHeuristic(game.tip.heuristic) }}</span>
                  <span class="confidence">{{ Math.round(game.tip.confidence * 100) }}%</span>
                </div>
                <div class="tip-body">
                  <h3>{{ getTeamDisplayName(game.tip.selected_team) }}</h3>
                  <p class="margin">Margin: {{ game.tip.margin }} pts</p>
                </div>
                <p v-if="game.tip?.explanation" class="explanation">{{ formatExplanation(game.tip.explanation) }}</p>
              </div>
              <div v-else class="no-tip">
                <p>No tip available</p>
              </div>

              </div>
            </NuxtLink>
          </div>
          </div>
        </Transition>
  </section>
  </template>
</template>

<script setup lang="ts">
import type {
  Game,
  GameDetailResponse,
  GameWithTip,
  GamesWithTipsResponse,
  LatestRoundResponse,
  MatchReportResponse,
} from '~/composables/useApi'
import { HEURISTIC_ORDER } from '~/composables/useFormatters'
import { AUTO_REFRESH_MS, resolveHomeState, useLatestRound } from '~/composables/useLatestRound'
const api = useApi()
const { getLogoUrl, getTeamDisplayName } = useTeamLogos()
const { formatHeuristic, formatDate: formatDateUtil, formatExplanation, getModelDisplayName } = useFormatters()

// ---------------------------------------------------------------------------
// UI state (declared first — the fetch watcher below reads it)
// ---------------------------------------------------------------------------
const selectedHeuristic = ref<string>('weighted_tip')

const heuristics = HEURISTIC_ORDER.map(value => ({
  value,
  label: formatHeuristic(value)
}))

const formatDate = formatDateUtil

// ---------------------------------------------------------------------------
// Data fetching — SEO-C1 / H-3 / M-4 (2026-09 review)
//
// This page used to fetch everything in onMounted (client-only), so the
// prerendered HTML shipped an empty shell to crawlers and social
// previews.  Fetching now happens in <setup> via useAsyncData: it runs
// at generate time (data is inlined into the prerendered HTML AND the
// Nuxt payload, so hydration needs no refetch), and re-runs reactively
// when the heuristic or round changes.
// ---------------------------------------------------------------------------
const { data: round, refresh: refreshRound } = await useAsyncData<LatestRoundResponse>(
  'latest-round',
  () => api.getLatestRound(),
)

// Publish the round into the shared store so passive consumers
// (OffSeasonBanner, ConfettiEffect) hydrate without fetching.
const { setLatestRound } = useLatestRound()
setLatestRound(round.value)

// Reactive season/round locator (falls back to current year / round 1).
const seasonRound = computed(() => ({
  season: round.value?.season ?? new Date().getFullYear(),
  round: round.value?.round_id ?? 1,
}))

// ---------------------------------------------------------------------------
// Home-page state (grand-final uplift, 2026-09)
//
// The latest-round locator drives three mutually-exclusive states:
//   1. grand_final — GF week (`is_grand_final && !is_post_season`): the
//      page becomes the pre-match grand-final report.
//   2. post_season — the GF round is fully completed: off-season
//      celebration with the premier.
//   3. regular — every other round: the original home page, unchanged.
// Gating lives in the pure `resolveHomeState` helper so it stays
// unit-testable without mounting this page.
// ---------------------------------------------------------------------------
const homeState = computed(() => resolveHomeState(round.value))
const isGrandFinal = computed(() => homeState.value === 'grand_final')
const isPostSeason = computed(() => homeState.value === 'post_season')

interface GrandFinalView {
  game: Game
  detail: GameDetailResponse | null
  report: MatchReportResponse | null
}

// Grand-final view: resolve the single GF game for the round, then load
// its detail + pre-match report in parallel.  Watched on `seasonRound`
// so a poller-driven round change refetches; `dedupe: 'cancel'` keeps a
// slow stale response from overwriting a newer round (same contract as
// the games-with-tips fetch below).
const {
  data: grandFinalData,
  pending: grandFinalPending,
  refresh: refreshGrandFinal,
} = await useAsyncData<GrandFinalView | null>(
  'grand-final-view',
  async () => {
    if (!isGrandFinal.value) return null
    const games = (await api.getGames({
      season: seasonRound.value.season,
      round: seasonRound.value.round,
    })) as Game[]
    const game = games.find(g => g.home_team && g.away_team)
    if (!game) return null
    // A missing report (404) is expected pre-generation: getGameReport
    // maps it to null and the page falls back to the detail experience.
    const [detail, report] = await Promise.all([
      api.getGameDetail(game.slug).catch(() => null),
      api.getGameReport(game.slug),
    ])
    return { game, detail, report }
  },
  {
    watch: [seasonRound],
    dedupe: 'cancel',
  },
)

const grandFinalGame = computed<Game | null>(() => grandFinalData.value?.game ?? null)
const grandFinalDetail = computed<GameDetailResponse | null>(() => grandFinalData.value?.detail ?? null)
const grandFinalReport = computed<MatchReportResponse | null>(() => grandFinalData.value?.report ?? null)

const { data: gamesData, pending: loading, error: gamesError, refresh: refreshGames } =
  await useAsyncData<GamesWithTipsResponse>(
    'games-with-tips',
    () => api.getGamesWithTips(seasonRound.value.season, seasonRound.value.round, selectedHeuristic.value),
    {
      // FIX H-3: `watch` + `dedupe: 'cancel'` means a rapid heuristic
      // switch cancels the in-flight request instead of letting a slow
      // stale response overwrite the newer selection (previously
      // last-RESOLVED won → wrong tips under the wrong tab).
      watch: [selectedHeuristic, seasonRound],
      dedupe: 'cancel',
    },
  )

const gamesWithTips = computed<GameWithTip[]>(() => gamesData.value?.games ?? [])

const error = computed<string | null>(() => {
  if (!gamesError.value) return null
  return 'Failed to load tips'
})

const refreshAll = async () => {
  await refreshRound()
  setLatestRound(round.value)
  await refreshGames()
}

// ---------------------------------------------------------------------------
// Client-side behaviour
// ---------------------------------------------------------------------------

// Restore the persisted heuristic preference (client-only).  Setting
// the ref triggers the useAsyncData watcher — no manual double fetch.
onMounted(() => {
  const stored = localStorage.getItem('selected-heuristic')
  if (stored && HEURISTIC_ORDER.includes(stored) && stored !== selectedHeuristic.value) {
    selectedHeuristic.value = stored
  }
})

// Auto-refresh: ONE poller, owned by this page (previously the page,
// OffSeasonBanner and ConfettiEffect each polled independently).  A
// round change flows through `seasonRound` and re-triggers the games
// fetch reactively.
let autoRefreshTimer: ReturnType<typeof setInterval> | null = null
onMounted(() => {
  autoRefreshTimer = setInterval(async () => {
    if (document.visibilityState !== 'visible') return
    try {
      await refreshRound()
      setLatestRound(round.value)
      // REVIEW-MAJOR-3: during GF week the report is generated by the
      // nightly cron — possibly AFTER this page loaded.  The round
      // locator doesn't change then, so the `grand-final-view` watcher
      // never refires on its own; keep polling until the report lands.
      if (isGrandFinal.value && !grandFinalReport.value) {
        await refreshGrandFinal()
      }
    } catch (e) {
      if (import.meta.dev) console.error('Auto-refresh failed:', e)
    }
  }, AUTO_REFRESH_MS)
})
onUnmounted(() => {
  if (autoRefreshTimer) {
    clearInterval(autoRefreshTimer)
    autoRefreshTimer = null
  }
})

// ---------------------------------------------------------------------------
// SEO — FX-05 / FX-20 / H-2 (2026-09 review) + grand-final uplift
// ---------------------------------------------------------------------------
// `useSeoMeta({ canonical })` was NOT a supported key — it silently
// rendered nothing.  Canonicals are <link> elements and go through
// useHead, using the siteUrl runtime config (below).
//
// Grand-final uplift: title/description are now state-aware getters —
// the grand-final week and post-season states each get their own meta,
// and the regular-state strings are byte-identical to the previous
// static meta.  titleTemplate (nuxt.config) already appends the site
// name, so the title strings below deliberately omit it.
const siteUrl = useRuntimeConfig().public.siteUrl as string

const homeMeta = computed(() => {
  if (isPostSeason.value) {
    const name = round.value?.premier ? getTeamDisplayName(round.value.premier) : null
    const season = round.value?.season
    const title = name ? `${name} — ${season} AFL Premiers` : 'AFL Off Season'
    const description = name
      ? `Congratulations to the ${name}, ${season} AFL premiers. The season is in the books — AI-powered AFL tips return next season.`
      : 'The AFL season is complete — AI-powered AFL tips and predictions return next season.'
    return { title, ogTitle: title, description, ogDescription: description, twitterTitle: title, twitterDescription: description }
  }
  if (isGrandFinal.value) {
    const g = grandFinalGame.value
    const matchup = g?.home_team && g?.away_team
      ? `${getTeamDisplayName(g.home_team)} vs ${getTeamDisplayName(g.away_team)}`
      : null
    const title = matchup
      ? `${matchup} — AFL Grand Final Tips & Prediction`
      : 'AFL Grand Final Tips & Prediction'
    const description = grandFinalReport.value?.report.executive_summary
      ?? 'The AFL grand final pre-match report: verdict, season story, keys to the game, players to watch and model consensus.'
    return { title, ogTitle: title, description, ogDescription: description, twitterTitle: title, twitterDescription: description }
  }
  return {
    title: 'AFL Tips & Predictions',
    ogTitle: 'AFL Tips & Predictions | AI-Powered Footy Tipping',
    description: 'Get AI-powered AFL tips and predictions for the current round. Expert footy tipping advice with smart heuristics, betting tips, and round predictions backed by machine learning models.',
    ogDescription: 'Get AI-powered AFL tips and predictions for the current round. Expert footy tipping advice with smart heuristics.',
    twitterTitle: 'AFL Tips & Predictions | AI-Powered Footy Tipping',
    twitterDescription: 'Get AI-powered AFL tips and predictions for the current round. Expert footy tipping advice with smart heuristics.',
  }
})

useSeoMeta({
  title: () => homeMeta.value.title,
  description: () => homeMeta.value.description,
  ogTitle: () => homeMeta.value.ogTitle,
  ogDescription: () => homeMeta.value.ogDescription,
  twitterTitle: () => homeMeta.value.twitterTitle,
  twitterDescription: () => homeMeta.value.twitterDescription,
})

useHead({
  link: [
    { rel: 'canonical', href: siteUrl }
  ],
  meta: [
    { name: 'keywords', content: 'AFL tips, AFL predictions, AFL betting tips, AFL footy tips, AFL round predictions, AFL betting advice, footy tipping, AFL betting' },
    { property: 'og:type', content: 'website' },
    { property: 'og:url', content: siteUrl }
  ],
  script: [
    {
      type: 'application/ld+json',
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'AFL Tips & Predictions',
        description: 'Get AI-powered AFL tips and predictions for the current round. Expert footy tipping advice with smart heuristics.',
        url: siteUrl,
        mainEntity: {
          '@type': 'SportsEvent',
          sport: 'Australian Rules Football',
          name: 'AFL Tips'
        }
      })
    }
  ]
})
</script>

<style scoped>
.hero {
  /* DESIGN-FIX (rhythm): the old 4rem bottom padding stacked with the
     section's 3rem top padding left a ~200px dead zone between the hero
     and the round strip. Tightened so the page breathes without a chasm. */
  padding: 3.5rem 1.5rem 2.25rem;
  text-align: center;
}

.hero h1 {
  font-size: clamp(2rem, 8vw, 6rem);
  line-height: 1.05;
  margin-bottom: 1rem;
}

.hero p {
  font-size: 1.125rem;
  max-width: 600px;
  margin: 0 auto;
}

.section {
  padding: 2.25rem 1.5rem 3rem;
}

/* Round Display */
.round-display {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.75rem;
  padding: 1rem 1.5rem;
  border: 1px solid var(--color-border);
  margin-bottom: 1.5rem;
  flex-wrap: wrap;
}

.round-label {
  font-size: 0.6875rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--color-muted);
}

.round-value {
  font-size: 1.25rem;
  font-weight: 800;
}

.game-count {
  font-size: 0.8125rem;
  color: var(--color-muted);
}

/* Data Warning
   DESIGN-FIX (identity): amber alert styling broke the monochrome
   language — a dashed border carries the "notice" weight instead. */
.data-warning {
  padding: 0.875rem 1.25rem;
  background: var(--color-hover);
  border: 1px dashed var(--color-text);
  border-radius: 0;
  margin-bottom: 1.5rem;
  text-align: center;
}

.data-warning p {
  margin: 0;
  font-size: 0.875rem;
  color: var(--color-text);
}

.data-warning strong {
  color: var(--color-text);
}

/* Heuristic Selector */
.heuristic-selector {
  display: flex;
  justify-content: center;
  gap: 0.5rem;
  margin-bottom: 2rem;
  flex-wrap: wrap;
}

.heuristic-btn {
  padding: 0.625rem 1.25rem;
  font-size: 0.8125rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border: 2px solid var(--color-border);
  background: var(--color-bg);
  color: var(--color-text);
  cursor: pointer;
  transition: all 0.2s ease;
  min-height: 44px;
  min-width: 44px;
}

.heuristic-btn:hover {
  border-color: var(--color-text);
}

.heuristic-btn.active {
  background: var(--color-text);
  color: var(--color-bg);
  border-color: var(--color-text);
}

.loading, .error, .empty {
  text-align: center;
  padding: 3rem 1.5rem;
}

.empty-hint {
  margin-top: 0.5rem;
  font-size: 0.875rem;
  color: var(--color-muted);
}

/* Games Grid */
.games-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
}

.game-card-link {
  display: block;
  cursor: pointer;
  transition: all 0.2s ease-in-out;
  text-decoration: none;
}

.game-card-link:hover {
  transform: translateY(-2px);
  box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1);
}

/* Match Info */
.game-card {
  border: 1px solid var(--color-border);
  padding: 1.5rem;
  height: 100%;
  /* DESIGN-FIX (rhythm): equal-height cards — the tip block fills the
     card so short explanations no longer leave a ragged void */
  display: flex;
  flex-direction: column;
}

.match-info {
  margin-bottom: 1.5rem;
  padding-bottom: 1.25rem;
  border-bottom: 1px solid var(--color-border);
}

.teams {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 0.75rem;
}

.team {
  flex: 1;
  font-size: 1.125rem;
  font-weight: 700;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.375rem;
}

.team.home {
  text-align: center;
  justify-content: center;
}

.team.away {
  text-align: center;
  justify-content: center;
}

.team-name {
  font-size: 0.8125rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  line-height: 1.2;
}

.team-logo {
  width: 40px;
  height: 40px;
  object-fit: contain;
}

.vs {
  font-size: 0.8125rem;
  font-weight: 700;
  padding: 0 0.75rem;
}

.match-details {
  display: flex;
  justify-content: space-between;
  font-size: 0.8125rem;
  color: var(--color-muted);
  flex-wrap: wrap;
  gap: 0.5rem;
}

/* Tip Info */
.tip-info {
  background: var(--color-hover);
  padding: 1.25rem;
  border-radius: 4px;
  /* Fill remaining card height so sibling cards align */
  flex: 1;
}

.tip-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.875rem;
  padding-bottom: 0.875rem;
  border-bottom: 1px solid var(--color-border);
}

.heuristic-badge {
  font-size: 0.6875rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--color-muted);
}

.confidence {
  font-size: 0.8125rem;
  font-weight: 700;
}

.tip-body h3 {
  font-size: 1.25rem;
  margin-bottom: 0.5rem;
}

.tip-body .margin {
  font-size: 0.8125rem;
  margin: 0;
}

.explanation {
  margin-top: 0.875rem;
  font-size: 0.875rem;
  line-height: 1.5;
  margin-bottom: 0;
  /* DESIGN-FIX (density): long AI explanations dominated the cards —
     clamp on the home grid; the full text lives on the game page */
  display: -webkit-box;
  -webkit-line-clamp: 5;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.no-tip {
  text-align: center;
  padding: 1.5rem;
  color: var(--color-muted);
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

/* Mobile styles */
@media (max-width: 640px) {
  .hero {
    padding: 2.5rem 1rem 1.75rem;
  }

  .hero h1 {
    margin-bottom: 1rem;
  }

  .hero p {
    font-size: 1rem;
  }

  .section {
    padding: 2rem 1rem;
  }

  .round-display {
    padding: 0.875rem 1rem;
    gap: 0.5rem;
  }

  .round-value {
    font-size: 1.125rem;
  }

  .heuristic-selector {
    margin-bottom: 1.5rem;
  }

  .heuristic-btn {
    padding: 0.5rem 1rem;
    font-size: 0.75rem;
  }

  .games-grid {
    grid-template-columns: 1fr;
    gap: 1rem;
  }

  .game-card {
    padding: 1.25rem;
  }

  .team {
    font-size: 1rem;
  }

  .vs {
    padding: 0 0.5rem;
    font-size: 0.75rem;
  }

  .tip-body h3 {
    font-size: 1.125rem;
  }

  .explanation {
    font-size: 0.8125rem;
  }

  .loading, .error, .empty {
    padding: 2rem 1rem;
  }
}

/* Tablet styles */
@media (min-width: 641px) and (max-width: 1024px) {
  .hero {
    padding: 5rem 1.5rem;
  }

  .games-grid {
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  }
}

/* Desktop styles */
@media (min-width: 1025px) {
  .hero {
    padding: 5rem 2rem 3rem;
  }

  .hero h1 {
    font-size: clamp(3rem, 10vw, 6rem);
    line-height: 0.95;
  }

  .hero p {
    font-size: 1.25rem;
  }

  .section {
    padding: 4rem 2rem;
    max-width: 1200px;
    margin: 0 auto;
  }

  .games-grid {
    grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
    gap: 2rem;
  }

  .game-card {
    padding: 2rem;
  }

  .team {
    font-size: 1.25rem;
  }

  .vs {
    font-size: 0.875rem;
    padding: 0 1rem;
  }

  .match-details {
    font-size: 0.875rem;
  }

  .tip-body h3 {
    font-size: 1.5rem;
  }

  .tip-body .margin {
    font-size: 0.875rem;
  }

  .explanation {
    font-size: 0.9375rem;
  }

  .heuristic-btn {
    padding: 0.75rem 1.5rem;
    font-size: 0.875rem;
  }

  .round-display {
    padding: 1.5rem;
    gap: 1rem;
  }

  .round-value {
    font-size: 1.5rem;
  }

  .game-count {
    font-size: 0.875rem;
  }

  .round-label {
    font-size: 0.75rem;
  }

  .heuristic-badge {
    font-size: 0.75rem;
  }

  .confidence {
    font-size: 0.875rem;
  }

}

/* ---------------------------------------------------------------------
   Grand-final fallback detail experience (report 404 → detail view).
   Markup patterns mirror pages/game/[slug].vue so the fallback feels
   identical to the game page it links to.
   --------------------------------------------------------------------- */
.gf-fallback {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.gf-header {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-left: 4px solid var(--color-text);
  padding: 2rem;
  text-align: center;
}

.gf-eyebrow {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 0.15em;
  border: 1px solid var(--color-text);
  padding: 0.375rem 0.875rem;
  margin-bottom: 1.25rem;
}

.gf-header .teams {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 2rem;
  margin-bottom: 1.25rem;
}

.gf-header .team {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.75rem;
  flex: 1;
}

.gf-header .team-logo {
  width: 80px;
  height: 80px;
  object-fit: contain;
}

.gf-header .team-name {
  font-weight: 700;
  font-size: 1.125rem;
}

.gf-header .vs {
  font-size: 1.125rem;
  font-weight: 700;
  color: var(--color-muted);
}

.game-meta {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem;
  padding-top: 1rem;
  border-top: 1px solid var(--color-border);
}

.meta-item {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.meta-item .label {
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--color-muted);
}

.meta-item .value {
  font-weight: 600;
}

.gf-section-block {
  margin: 0;
}

/* REVIEW-MAJOR-3: manual adoption affordance while the report is
   pending (poller picks it up automatically between clicks). */
.gf-report-hint {
  margin-bottom: 2rem;
  text-align: center;
}

.section-title {
  font-size: 1.5rem;
  font-weight: 700;
  margin: 0 0 1.5rem;
}

.tips-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 1rem;
}

.models-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1rem;
}

.model-card {
  border: 1px solid var(--color-border);
  padding: 1.5rem;
  transition: border-color 0.2s ease;
}

.model-card:hover {
  border-color: var(--color-text);
}

.model-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
  padding-bottom: 0.75rem;
  border-bottom: 1px solid var(--color-border);
}

.model-name {
  font-size: 0.6875rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--color-muted);
}

.model-header .confidence {
  font-size: 0.8125rem;
  font-weight: 700;
}

.model-body h3 {
  font-size: 1.25rem;
  margin-bottom: 0.5rem;
}

.model-body .margin {
  font-size: 0.8125rem;
  margin: 0;
  color: var(--color-muted);
}

.gf-unavailable {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
  text-align: center;
}

.gf-unavailable p {
  margin: 0;
  color: var(--color-muted);
}

@media (max-width: 640px) {
  .gf-header {
    padding: 1.5rem 1rem;
  }

  .gf-header .teams {
    gap: 1rem;
  }

  .gf-header .team-logo {
    width: 64px;
    height: 64px;
  }

  .gf-header .team-name {
    font-size: 1rem;
  }

  .gf-header .vs {
    font-size: 1rem;
  }

  .tips-grid,
  .models-grid {
    grid-template-columns: 1fr;
  }

  .section-title {
    font-size: 1.25rem;
  }
}

@media (min-width: 641px) and (max-width: 1024px) {
  .gf-header .team-logo {
    width: 72px;
    height: 72px;
  }
}

@media (min-width: 1025px) {
  .gf-header {
    padding: 2.5rem;
  }

  .gf-header .team-logo {
    width: 96px;
    height: 96px;
  }

  .gf-header .team-name {
    font-size: 1.25rem;
  }
}
</style>
