"""Initial migration

Revision ID: 48910ce1b31b
Revises: 
Create Date: 2026-03-30 23:20:19.742188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48910ce1b31b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'games',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('squiggle_id', sa.Integer(), nullable=True),
        sa.Column('round_id', sa.Integer(), nullable=True),
        sa.Column('season', sa.Integer(), nullable=True),
        sa.Column('home_team', sa.String(length=100), nullable=True),
        sa.Column('away_team', sa.String(length=100), nullable=True),
        sa.Column('home_score', sa.Integer(), nullable=True),
        sa.Column('away_score', sa.Integer(), nullable=True),
        sa.Column('venue', sa.String(length=200), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('completed', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_date'), 'games', ['date'], unique=False)
    op.create_index(op.f('ix_games_home_team'), 'games', ['home_team'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_round_id'), 'games', ['round_id'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_squiggle_id'), 'games', ['squiggle_id'], unique=True)
    op.create_index(op.f('ix_games_venue'), 'games', ['venue'], unique=False)
    op.create_table(
        'tips',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=True),
        sa.Column('heuristic', sa.String(length=50), nullable=True),
        sa.Column('selected_team', sa.String(length=100), nullable=True),
        sa.Column('margin', sa.Integer(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_game_id'), 'tips', ['game_id'], unique=False)
    op.create_index(op.f('ix_tip_heuristic'), 'tips', ['heuristic'], unique=False)
    op.create_index(op.f('ix_tip_id'), 'tips', ['id'], unique=False)
    op.create_table(
        'backtest_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('heuristic', sa.String(length=50), nullable=True),
        sa.Column('season', sa.Integer(), nullable=True),
        sa.Column('round_id', sa.Integer(), nullable=True),
        sa.Column('tips_made', sa.Integer(), nullable=True),
        sa.Column('tips_correct', sa.Integer(), nullable=True),
        sa.Column('accuracy', sa.Float(), nullable=True),
        sa.Column('profit', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('heuristic', 'round_id', 'season', name='uq_backtest_season_round_heuristic')
    )
    op.create_index(op.f('ix_backtest_results_heuristic'), 'backtest_results', ['heuristic'], unique=False)
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_results_round_id'), 'backtest_results', ['round_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_season'), 'backtest_results', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_results_season'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_round_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_heuristic'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_tip_id'), table_name='tips')
    op.drop_index(op.f('ix_tip_heuristic'), table_name='tips')
    op.drop_index(op.f('ix_tip_game_id'), table_name='tips')
    op.drop_table('tips')
    op.drop_index(op.f('ix_games_venue'), table_name='games')
    op.drop_index(op.f('ix_games_squiggle_id'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_round_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team'), table_name='games')
    op.drop_index(op.f('ix_games_date'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
