"""Add cron job tables and sync tracking

Revision ID: 9a1b2c3d4e5f
Revises: 0fc5de95b2f1
Create Date: 2026-04-02 13:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1b2c3d4e5f'
down_revision: Union[str, Sequence[str], None] = '0fc5de95b2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create job_executions table
    op.create_table(
        'job_executions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_name', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('items_processed', sa.Integer(), nullable=True),
        sa.Column('items_failed', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('result_summary', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_executions_job_name'), 'job_executions', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_executions_status'), 'job_executions', ['status'], unique=False)
    op.create_index(op.f('ix_job_executions_started_at'), 'job_executions', ['started_at'], unique=False)
    op.create_index('ix_job_executions_job_started', 'job_executions', ['job_name', 'started_at'], unique=False)
    
    # Create job_locks table
    op.create_table(
        'job_locks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_name', sa.String(length=100), nullable=False),
        sa.Column('locked_at', sa.DateTime(), nullable=False),
        sa.Column('locked_by', sa.String(length=100), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('job_name', name='uq_job_locks_job_name')
    )
    op.create_index(op.f('ix_job_locks_expires_at'), 'job_locks', ['expires_at'], unique=False)
    
    # Create elo_cache table
    op.create_table(
        'elo_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('team_name', sa.String(length=100), nullable=False),
        sa.Column('rating', sa.Float(), nullable=False),
        sa.Column('games_played', sa.Integer(), nullable=False),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.Column('season', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('team_name', name='uq_elo_cache_team_name')
    )
    op.create_index(op.f('ix_elo_cache_team_name'), 'elo_cache', ['team_name'], unique=False)
    
    # Modify games table to add sync tracking fields
    with op.batch_alter_table('games', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.Integer(), server_default=sa.text('0'), nullable=False))
    
    # Modify generation_progress table to add job_execution_id
    with op.batch_alter_table('generation_progress', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('job_execution_id', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes first
    op.drop_index('ix_job_executions_job_started', table_name='job_executions')
    op.drop_index(op.f('ix_job_executions_started_at'), table_name='job_executions')
    op.drop_index(op.f('ix_job_executions_status'), table_name='job_executions')
    op.drop_index(op.f('ix_job_executions_job_name'), table_name='job_executions')
    
    op.drop_index(op.f('ix_job_locks_expires_at'), table_name='job_locks')
    
    op.drop_index(op.f('ix_elo_cache_team_name'), table_name='elo_cache')
    
    # Drop tables
    op.drop_table('job_executions')
    op.drop_table('job_locks')
    op.drop_table('elo_cache')
    
    # Revert games table modifications
    with op.batch_alter_table('games', recreate='always') as batch_op:
        batch_op.drop_column('sync_version')
        batch_op.drop_column('last_synced_at')
    
    # Revert generation_progress table modifications
    with op.batch_alter_table('generation_progress', recreate='always') as batch_op:
        batch_op.drop_column('job_execution_id')
    
    # ### end Alembic commands ###
