"""add_status_tracking_to_games

Revision ID: a1b2c3d4e5f6
Revises: c786defe6998
Create Date: 2026-03-31 17:56:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'c786defe6998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add predictions_generated column
    op.add_column(
        'games',
        sa.Column('predictions_generated', sa.Boolean(), nullable=False, server_default='0')
    )
    
    # Add tips_generated column
    op.add_column(
        'games',
        sa.Column('tips_generated', sa.Boolean(), nullable=False, server_default='0')
    )
    
    # Create indexes for the new columns
    op.create_index(op.f('ix_games_predictions_generated'), 'games', ['predictions_generated'], unique=False)
    op.create_index(op.f('ix_games_tips_generated'), 'games', ['tips_generated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_games_tips_generated'), table_name='games')
    op.drop_index(op.f('ix_games_predictions_generated'), table_name='games')
    
    # Drop columns
    op.drop_column('games', 'tips_generated')
    op.drop_column('games', 'predictions_generated')
    # ### end Alembic commands ###
