"""sync_model_and_migrations

Revision ID: 0fc5de95b2f1
Revises: ddf16b980603
Create Date: 2026-03-31 18:40:21.522569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc5de95b2f1'
down_revision: Union[str, Sequence[str], None] = 'ddf16b980603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to handle constraint changes
    with op.batch_alter_table('backtest_results', recreate='always') as batch_op:
        batch_op.create_unique_constraint('uq_backtest_season_round_heuristic', ['season', 'round_id', 'heuristic'])

    with op.batch_alter_table('games', recreate='always') as batch_op:
        batch_op.alter_column('predictions_generated', nullable=True, existing_type=sa.BOOLEAN(), existing_server_default=sa.text("'0'"))
        batch_op.alter_column('tips_generated', nullable=True, existing_type=sa.BOOLEAN(), existing_server_default=sa.text("'0'"))
        batch_op.drop_index('ix_games_season_round')
        batch_op.drop_index('ix_games_season_round_completed')

    with op.batch_alter_table('tips', recreate='always') as batch_op:
        batch_op.drop_index('uq_game_heuristic')
        batch_op.create_unique_constraint('uq_game_heuristic', ['game_id', 'heuristic'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', recreate='always') as batch_op:
        batch_op.drop_constraint('uq_game_heuristic', type_='unique')
        batch_op.create_index('uq_game_heuristic', ['game_id', 'heuristic'], unique=True)

    with op.batch_alter_table('games', recreate='always') as batch_op:
        batch_op.create_index('ix_games_season_round_completed', ['season', 'round_id', 'completed'], unique=False)
        batch_op.create_index('ix_games_season_round', ['season', 'round_id'], unique=False)
        batch_op.alter_column('tips_generated', nullable=False, existing_type=sa.BOOLEAN(), existing_server_default=sa.text("'0'"))
        batch_op.alter_column('predictions_generated', nullable=False, existing_type=sa.BOOLEAN(), existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('backtest_results', recreate='always') as batch_op:
        batch_op.drop_constraint('uq_backtest_season_round_heuristic', type_='unique')
    # ### end Alembic commands ###
