"""add_composite_indexes

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-03-31 10:24:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create composite index for fetching games by season and round
    op.create_index(
        op.f('ix_games_season_round'),
        'games',
        ['season', 'round_id'],
        unique=False
    )
    
    # Create composite index for filtering incomplete games by round
    op.create_index(
        op.f('ix_games_season_round_completed'),
        'games',
        ['season', 'round_id', 'completed'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop composite indexes
    op.drop_index(op.f('ix_games_season_round_completed'), table_name='games')
    op.drop_index(op.f('ix_games_season_round'), table_name='games')
    # ### end Alembic commands ###
