"""add_unique_constraint_to_tips

Revision ID: 4a4ab87d9071
Revises: 48910ce1b31b
Create Date: 2026-03-31 00:03:58.184524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4ab87d9071'
down_revision: Union[str, Sequence[str], None] = '48910ce1b31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER TABLE ADD CONSTRAINT, so we use CREATE UNIQUE INDEX
    # Unique constraint for backtest_results table
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS uq_backtest_season_round_heuristic ON backtest_results(season, round_id, heuristic)')
    
    # Unique constraint for tips table
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS uq_game_heuristic ON tips(game_id, heuristic)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS uq_game_heuristic')
    op.execute('DROP INDEX IF EXISTS uq_backtest_season_round_heuristic')
    # ### end Alembic commands ###
