"""Create match_reports table for grand-final pre-match reports

Adds ``match_reports`` — one structured JSONB report per game
(unique on ``game_id``), currently holding the grand-final PRE-match
report generated by the Pydantic AI research agent
(``report_type = 'grand_final_pre_match'``).

Revision ID: 0008_match_reports
Revises: 0007_elo_cache_dedup
Create Date: 2026-09-19 12:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008_match_reports"
down_revision: Union[str, Sequence[str], None] = "0007_elo_cache_dedup"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create ``match_reports`` (one structured report per game)."""
    op.create_table(
        "match_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column(
            "report_type",
            sa.String(length=50),
            nullable=False,
            server_default=sa.text("'grand_final_pre_match'"),
        ),
        sa.Column("report", JSONB, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", name="uq_match_reports_game_id"),
    )
    op.create_index("ix_match_reports_id", "match_reports", ["id"], unique=False)
    op.create_index(
        "ix_match_reports_game_id", "match_reports", ["game_id"], unique=True
    )
    op.create_index(
        "ix_match_reports_report_type", "match_reports", ["report_type"], unique=False
    )


def downgrade() -> None:
    """Drop the ``match_reports`` table."""
    op.drop_index("ix_match_reports_report_type", table_name="match_reports")
    op.drop_index("ix_match_reports_game_id", table_name="match_reports")
    op.drop_index("ix_match_reports_id", table_name="match_reports")
    op.drop_table("match_reports")
