from fastapi import APIRouter, Depends, HTTPException, Query, BackgroundTasks
from sqlalchemy.ext.asyncio import AsyncSession
from slowapi import Limiter
from slowapi.util import get_remote_address
from typing import Optional

from app.db import get_db
from app.crud import TipCRUD, GameCRUD
from app.schemas import TipResponse, TipListResponse
from app.orchestrator import ModelOrchestrator
from app.services import ExplanationService

router = APIRouter()
limiter = Limiter(key_func=get_remote_address)
orchestrator = ModelOrchestrator()


@router.get("", response_model=TipListResponse)
@limiter.limit("60/minute")
async def get_tips(
    heuristic: Optional[str] = Query(None, description="Filter by heuristic type"),
    season: Optional[int] = Query(None, description="Filter by season year"),
    round_id: Optional[int] = Query(None, alias="round", description="Filter by round number"),
    db: AsyncSession = Depends(get_db),
):
    """Get tips with optional filtering."""
    if season and round_id:
        tips = await TipCRUD.get_by_round(db, season, round_id)
    elif heuristic:
        tips = await TipCRUD.get_by_heuristic(db, heuristic)
    else:
        # Return recent tips
        tips = await TipCRUD.get_by_heuristic(db, "best_bet", limit=50)
    
    return TipListResponse(
        tips=[TipResponse.model_validate(t) for t in tips],
        count=len(tips),
    )


@router.get("/{heuristic}", response_model=TipListResponse)
@limiter.limit("60/minute")
async def get_tips_by_heuristic(
    heuristic: str,
    limit: int = Query(100, ge=1, le=500),
    db: AsyncSession = Depends(get_db),
):
    """Get tips by heuristic type."""
    tips = await TipCRUD.get_by_heuristic(db, heuristic, limit=limit)
    return TipListResponse(
        tips=[TipResponse.model_validate(t) for t in tips],
        count=len(tips),
    )


@router.post("/generate")
@limiter.limit("10/minute")
async def generate_tips(
    background_tasks: BackgroundTasks,
    season: int = Query(..., description="Season year"),
    round_id: int = Query(..., alias="round", description="Round number"),
    heuristics: Optional[list[str]] = Query(None, description="Heuristics to generate (default: all)"),
    generate_explanations: bool = Query(True, description="Generate AI explanations"),
    db: AsyncSession = Depends(get_db),
):
    """Generate tips for a round using ML models and heuristics."""
    # Get games for the round
    games = await GameCRUD.get_by_round(db, season, round_id)
    
    if not games:
        raise HTTPException(status_code=404, detail="No games found for this round")
    
    # Determine which heuristics to use
    if heuristics:
        heuristics_to_use = [h for h in heuristics if h in orchestrator.get_available_heuristics()]
    else:
        heuristics_to_use = orchestrator.get_available_heuristics()
    
    # Generate tips
    tips_created = []
    for game in games:
        # Delete existing tips for this game
        await TipCRUD.delete_for_game(db, game.id)
        
        for heuristic in heuristics_to_use:
            winner, confidence, margin = await orchestrator.predict(game, heuristic)
            
            # Note: Explanation will be generated by OpenRouter if requested
            tip = await TipCRUD.create(
                db=db,
                game_id=game.id,
                heuristic=heuristic,
                selected_team=winner,
                margin=margin,
                confidence=confidence,
                explanation="",  # Will be filled by AI if requested
            )
            tips_created.append(tip)
    
    # Generate explanations in background if requested
    if generate_explanations:
        async def generate_expl():
            service = ExplanationService()
            try:
                await service.generate_for_round(db, season, round_id)
            finally:
                await service.close()
        
        background_tasks.add_task(generate_expl)
    
    return {
        "message": f"Generated {len(tips_created)} tips for round {round_id}, {season}",
        "heuristics_used": heuristics_to_use,
        "tips_count": len(tips_created),
        "explanations_generating": generate_explanations,
    }


@router.post("/explanations/generate")
@limiter.limit("5/minute")
async def generate_explanations(
    season: int = Query(..., description="Season year"),
    round_id: int = Query(..., alias="round", description="Round number"),
    db: AsyncSession = Depends(get_db),
):
    """Generate AI explanations for tips in a round."""
    service = ExplanationService()
    
    try:
        count = await service.generate_for_round(db, season, round_id)
        return {
            "message": f"Generated {count} explanations for round {round_id}, {season}",
            "count": count,
        }
    finally:
        await service.close()
